version: "3.8"

services:
  app:
    image: sitiritis/devops_lab_1-2:1.0
    container_name: devops_lab1
    ports:
      - 5000:80

# Comment previous and uncomment this to build locally
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: devops_lab1-2
#    container_name: devops_lab1-2
#    ports:
#      - 5000:80
