version: "3.8"

x-base-app: &base-app
  build:
    context: .
    dockerfile: dev.Dockerfile
  image: sitiritis/iu-devops_dev
  environment:
    FLASK_ENV: development
    FLASK_DEBUG: 1
  volumes:
    - ./:/app

services:
  app:
    <<: *base-app
    container_name: sitiritis/iu-devops_dev
    ports:
      - "5000:80"

  test:
    <<: *base-app
    container_name: sitiritis/iu-devops_dev-test
    entrypoint: pytest

  mypy:
    <<: *base-app
    container_name: sitiritis/iu-devops_dev-mypy
    entrypoint: mypy

  pylama:
    <<: *base-app
    container_name: sitiritis/iu-devops_dev-pylama
    entrypoint: pylama

  format:
    <<: *base-app
    container_name: sitiritis/iu-devops_dev-format
    entrypoint: ./format-entrypoint.sh
