version: '3.8'

services:
  app:
    image: sitiritis/iu-devops:latest
    container_name: tymur-lysenko-iu-devops-app
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    networks:
      - monitoring
    ports:
      - "5000:80"
    volumes:
      - ./workdir/log:/var/log/sitirits-iu-devops

  prometheus:
    image: prom/prometheus:v2.30.0
    container_name: tymur-lysenko-iu-devops-prom
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  promtail:
    image: grafana/promtail:2.3.0
    container_name: tymur-lysenko-iu-devops-promtail
    networks:
      - monitoring
    volumes:
      - ./conf/promtail:/etc/promtail
      - ./workdir/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  loki:
    image: grafana/loki:2.3.0
    container_name: tymur-lysenko-iu-devops-loki
    networks:
      - monitoring
    ports:
      - "3100:3100"
    volumes:
      - ./conf/loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:8.1.3
    container_name: tymur-lysenko-iu-devops-grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"

networks:
  monitoring: {}
