version: '3.8'

services:
  app:
    image: sitiritis/iu-devops:latest
    container_name: tymur-lysenko-iu-devops-app
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    ports:
      - "5000:80"
    volumes:
      - ./workdir/log:/var/log/sitirits-iu-devops

  promtail:
    image: grafana/promtail:2.3.0
    container_name: tymur-lysenko-iu-devops-promtail
    networks:
      - loki
    volumes:
      - ./conf/promtail:/etc/promtail
      - ./workdir/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  loki:
    image: grafana/loki:2.3.0
    container_name: tymur-lysenko-iu-devops-loki
    networks:
      - loki
    ports:
      - "3100:3100"
    volumes:
      - ./conf/loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:8.1.3
    container_name: tymur-lysenko-iu-devops-grafana
    networks:
      - loki
    ports:
      - "3000:3000"

networks:
  loki: {}
