---
- name: Create a docker-compose directory if it does not exist
  file:
    path: "{{ docker_compose_dir }}"
    state: directory

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: "{{ docker_compose_dir }}/docker-compose.yml"

- name: Pull and restart containers
  docker_compose:
    project_src: "{{ docker_compose_dir }}"
    project_name: tymur-lysenko-iu-devops
    pull: yes
    state: present
    recreate: always
