---
- name: Download docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Create symbolic link for docker-compose executable
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
