apiVersion: v1
kind: Secret
metadata:
  name: sitiritis-iu-devops-lab-11
  labels:
    app: app-python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  secret_key: '{{ .Values.secret | b64enc }}'
