apiVersion: v1
kind: Secret
metadata:
  name: default
  labels:
    app: sitiritis-iu-devops-app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  secret_key: '{{ .Values.secret | b64enc }}'
