name: Build docker image and push to registry
on:
  push:
    branches:
      - 'master'
jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          default_bump: minor
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  build_and_push_docker_image:
    name: Build docker image & push to registry
    runs-on: ubuntu-20.04
    needs:
      - bump_version
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app_python
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: sitiritis/iu-devops:${{ needs.bump_version.outputs.new_tag }},sitiritis/iu-devops:latest
